#Ê±ÐòÔ¼Êø
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]

create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property -dict {PACKAGE_PIN R4 IOSTANDARD LVCMOS33} [get_ports sys_clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sys_clk]
set_property -dict {PACKAGE_PIN U2 IOSTANDARD LVCMOS33} [get_ports sys_rst_n]

set_property PACKAGE_PIN V9 [get_ports {da_data[0]}]
set_property PACKAGE_PIN AA8 [get_ports {da_data[9]}]
set_property PACKAGE_PIN AB8 [get_ports {da_data[8]}]
set_property PACKAGE_PIN AB6 [get_ports {da_data[7]}]
set_property PACKAGE_PIN V7 [get_ports {da_data[6]}]
set_property PACKAGE_PIN AB7 [get_ports {da_data[5]}]
set_property PACKAGE_PIN U7 [get_ports {da_data[4]}]
set_property PACKAGE_PIN V8 [get_ports {da_data[3]}]
set_property PACKAGE_PIN Y9 [get_ports {da_data[2]}]
set_property PACKAGE_PIN W9 [get_ports {da_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk]
set_property PACKAGE_PIN Y8 [get_ports da_clk]

set_property PACKAGE_PIN P15 [get_ports {da_data1[9]}]
set_property PACKAGE_PIN R16 [get_ports {da_data1[8]}]
set_property PACKAGE_PIN P17 [get_ports {da_data1[7]}]
set_property PACKAGE_PIN N17 [get_ports {da_data1[6]}]
set_property PACKAGE_PIN R18 [get_ports {da_data1[5]}]
set_property PACKAGE_PIN V20 [get_ports {da_data1[4]}]
set_property PACKAGE_PIN T18 [get_ports {da_data1[3]}]
set_property PACKAGE_PIN V19 [get_ports {da_data1[2]}]
set_property PACKAGE_PIN U17 [get_ports {da_data1[1]}]
set_property PACKAGE_PIN U18 [get_ports {da_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_data1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk1]
set_property PACKAGE_PIN R14 [get_ports da_clk1]
